on:
  schedule:
  - cron: '5,30,40 * * * *'

name: Build and upload llorgarm64linux compiler changeset build

jobs:
  build_llorgarm64linux:
    name: Build llorgarm64linux compiler
    runs-on: ubuntu-latest
    steps:
      - name: Prepare tools
        run: |
          mv /bin/tar /bin/tar-real
          echo '#!/bin/bash' >/bin/tar
          echo '/bin/tar-real "${@}" --no-same-owner' >>/bin/tar
          chmod +x /bin/tar
          echo 'deb [arch=amd64] http://repo-dpd-lde.inn.intel.com/lde.v3/debian/UBUNTU.1804.2/ia32e/source bionic main restricted' >> /etc/apt/sources.list
          echo 'i386' >> /var/lib/dpkg/arch
          apt-get update
          apt-get -yq install build-essential\
                        git\
                        python3-pip\
                        ninja-build\
                        g++-7-aarch64-linux-gnu\
                        g++-7-multilib-arm-linux-gnueabihf\
                        binutils-arm-linux-gnueabihf\
                        binutils-multiarch-dev\
                        libgcc1-armhf-cross\
                        libsfgcc1-armhf-cross\
                        libstdc++6-armhf-cross\
                        libstdc++-7-dev-armhf-cross
          python3 -m pip install cmake
          apt-get autoclean
          mkdir -p /home/cross
          mv /usr/bin/ssh /usr/bin/ssh-real
          echo '#!/bin/bash' >/usr/bin/ssh
          echo 'if [ -z "$HOST_USER" ]; then /usr/bin/ssh-real "${@}"; else /usr/bin/ssh-real -l "$HOST_USER" "${@}"; fi' >>/usr/bin/ssh
          chmod +x /usr/bin/ssh
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build llorgarm64linux compiler on ubuntu18
        run: |
          echo "env set up ok"
      - name: Upload llorgarm64linux build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: llorgarm64linux
          path: llorgarm64linux.tar.xz
